const phrases = [
  {id:'water',cat:'식당',icon:'🍱',jp:'お水をいただけますか？',romaji:'오미즈오 이타다케마스카?',ko:'물을 받을 수 있을까요?',use:'식당에서 물을 정중하게 요청할 때 사용해요.',note:'일본 식당에서는 물이 무료로 제공되는 경우가 많습니다.'},
  {id:'takeout',cat:'식당',icon:'🍱',jp:'持ち帰りできますか？',romaji:'모치카에리 데키마스카?',ko:'포장 가능한가요?',use:'남은 음식이나 메뉴를 포장하고 싶을 때 사용해요.',note:'“테이크아웃”보다 持ち帰り가 자연스럽습니다.'},
  {id:'check',cat:'식당',icon:'🍱',jp:'お会計をお願いします。',romaji:'오카이케이오 오네가이시마스.',ko:'계산 부탁드립니다.',use:'식사를 마친 뒤 계산을 요청할 때 사용해요.',note:'직원을 부를 때는 すみません을 먼저 붙이면 더 자연스럽습니다.'},
  {id:'station',cat:'교통',icon:'🚃',jp:'駅までお願いします。',romaji:'에키마데 오네가이시마스.',ko:'역까지 부탁드립니다.',use:'택시 기사님께 목적지를 말할 때 사용해요.',note:'지도 화면을 함께 보여주면 훨씬 정확합니다.'},
  {id:'ticket',cat:'교통',icon:'🚃',jp:'この電車は東京駅に行きますか？',romaji:'코노 덴샤와 도쿄에키니 이키마스카?',ko:'이 전철은 도쿄역에 가나요?',use:'전철이나 지하철을 타기 전 목적지를 확인할 때 사용해요.',note:'駅 이름만 바꾸어 어디서든 활용할 수 있어요.'},
  {id:'price',cat:'쇼핑',icon:'🛍️',jp:'これはいくらですか？',romaji:'코레와 이쿠라데스카?',ko:'이건 얼마인가요?',use:'물건의 가격을 물어볼 때 사용하는 기본 표현이에요.',note:'가격표를 가리키며 말하면 더 빠르게 통합니다.'},
  {id:'card',cat:'쇼핑',icon:'🛍️',jp:'カードは使えますか？',romaji:'카아도와 츠카에마스카?',ko:'카드 사용할 수 있나요?',use:'결제 전 카드 사용 가능 여부를 확인할 때 사용해요.',note:'작은 가게는 현금만 받는 곳도 있어요.'},
  {id:'checkin',cat:'숙소',icon:'🛎️',jp:'チェックインをお願いします。',romaji:'첵쿠인오 오네가이시마스.',ko:'체크인 부탁드립니다.',use:'호텔 프런트에서 예약자 이름을 말하기 전에 사용해요.',note:'예약 확인서나 여권을 함께 준비하세요.'},
  {id:'direction',cat:'길 묻기',icon:'🧭',jp:'駅はどこですか？',romaji:'에키와 도코데스카?',ko:'역은 어디인가요?',use:'가까운 역의 위치를 물어볼 때 사용해요.',note:'가게, 화장실 등 목적지만 바꾸어 사용할 수 있어요.'},
  {id:'help',cat:'긴급 상황',icon:'🆘',jp:'助けてください。',romaji:'타스케테 쿠다사이.',ko:'도와주세요.',use:'위험하거나 긴급히 도움이 필요할 때 사용해요.',note:'긴급 상황에서는 110(경찰), 119(구급·소방)로 전화하세요.'}
];
const categories=[['식당','🍱','#f8e3c5','식사와 주문'],['교통','🚃','#dce8ed','전철과 택시'],['쇼핑','🛍️','#f1dce5','가격과 결제'],['숙소','🛎️','#e7e2ce','체크인과 요청'],['길 묻기','🧭','#dce8d7','장소와 방향'],['긴급 상황','🆘','#f0d6cd','도움이 필요할 때']];
let current=[],history=[],activePhrase=null;let favorites=JSON.parse(localStorage.getItem('tabi-favorites')||'[]');
const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);
function show(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id+'-screen').classList.add('active');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));window.scrollTo(0,0)}
function updateFavorites(){localStorage.setItem('tabi-favorites',JSON.stringify(favorites));$('#favorite-count').textContent=favorites.length}
function speak(text){const utterance=new SpeechSynthesisUtterance(text);utterance.lang='ja-JP';utterance.rate=.82;speechSynthesis.cancel();speechSynthesis.speak(utterance)}
function renderCategories(){$('#category-grid').innerHTML=categories.map(([name,emoji,color,sub])=>`<button class="category-card" data-cat="${name}" style="--card:${color}"><span class="emoji">${emoji}</span><strong>${name}</strong><small>${sub}</small></button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>openList(b.dataset.cat))}
function openList(cat){current=cat==='popular'?phrases.slice(0,7):cat==='favorites'?phrases.filter(p=>favorites.includes(p.id)):phrases.filter(p=>p.cat===cat);$('#list-eyebrow').textContent=cat==='favorites'?'SAVED PHRASES':cat==='popular'?'QUICK ACCESS':'SITUATION';$('#list-title').textContent=cat==='popular'?'자주 쓰는 말':cat==='favorites'?'저장한 표현':cat;$('#list-description').textContent=current.length?`${current.length}개의 표현을 준비했어요.`:'아직 저장한 표현이 없어요.';$('#phrase-list').innerHTML=current.map(p=>`<article class="phrase-card" data-id="${p.id}"><button class="speaker" data-speak="${p.id}" aria-label="듣기">▶</button><div class="jp">${p.jp}</div><div class="ko">${p.ko}</div></article>`).join('');$$('.phrase-card').forEach(x=>x.onclick=e=>{if(!e.target.dataset.speak)openDetail(x.dataset.id)});$$('[data-speak]').forEach(x=>x.onclick=e=>{e.stopPropagation();speak(phrases.find(p=>p.id===x.dataset.speak).jp)});show('list')}
function openDetail(id){activePhrase=phrases.find(p=>p.id===id);history.push('list');const p=activePhrase;$('#detail-category').textContent=p.cat;$('#detail-japanese').textContent=p.jp;$('#detail-romaji').textContent=p.romaji;$('#detail-korean').textContent=p.ko;$('#detail-use').textContent=p.use;$('#detail-note').textContent=p.note;const related=phrases.filter(x=>x.cat===p.cat&&x.id!==p.id).slice(0,2);$('#detail-related-wrap').style.display=related.length?'block':'none';$('#detail-related').innerHTML=related.map(x=>`<div class="related-item" data-id="${x.id}"><strong>${x.jp}</strong><span>${x.ko}</span></div>`).join('');$$('.related-item').forEach(x=>x.onclick=()=>openDetail(x.dataset.id));const f=$('#detail-favorite');f.textContent=favorites.includes(p.id)?'♥':'♡';f.style.color=favorites.includes(p.id)?'var(--accent)':'var(--ink)';show('detail')}
function answer(question){const q=question.toLowerCase();let found=phrases.find(p=>q.includes('물')?p.id==='water':q.includes('포장')?p.id==='takeout':q.includes('체크인')||q.includes('호텔')?p.id==='checkin':q.includes('역')||q.includes('택시')?p.id==='station':q.includes('가격')||q.includes('얼마')?p.id==='price':q.includes('카드')?p.id==='card':q.includes('길')?p.id==='direction':q.includes('도움')?p.id==='help':false)||phrases[0];$('#ask-answer').innerHTML=`<article class="ai-card"><p class="eyebrow">TABi'S RECOMMENDATION</p><h3>${found.jp}</h3><p class="answer-ko">${found.romaji}<br/>${found.ko}</p><small>${found.use}<br/>${found.note}</small><br/><button data-answer-speak="${found.id}">▶ 일본어로 듣기</button></article>`;$('[data-answer-speak]').onclick=()=>speak(found.jp)}
$('#global-search').oninput=e=>{const v=e.target.value.trim();$('#search-results').innerHTML=v?phrases.filter(p=>(p.jp+p.ko+p.romaji).toLowerCase().includes(v.toLowerCase())).slice(0,4).map(p=>`<button class="search-result" data-id="${p.id}"><span><strong>${p.jp}</strong><small>${p.ko}</small></span><b>›</b></button>`).join('')||'<p style="color:#817c74;font-size:13px">찾는 표현이 없어요. AI에게 물어보세요.</p>':'';$$('.search-result').forEach(x=>x.onclick=()=>openDetail(x.dataset.id))};
$('#popular-button').onclick=()=>openList('popular');$('#favorites-button').onclick=()=>openList('favorites');$$('[data-back]').forEach(x=>x.onclick=()=>show(history.pop()||'home'));$('#detail-listen').onclick=()=>speak(activePhrase.jp);$('#detail-favorite').onclick=()=>{const i=favorites.indexOf(activePhrase.id);i<0?favorites.push(activePhrase.id):favorites.splice(i,1);updateFavorites();openDetail(activePhrase.id)};$$('.nav-item').forEach(x=>x.onclick=()=>x.dataset.nav==='favorites'?openList('favorites'):show(x.dataset.nav));$('#ask-form').onsubmit=e=>{e.preventDefault();const v=$('#ask-input').value.trim();if(v){answer(v);$('#ask-input').value=''}};$$('#suggestion-chips button').forEach(x=>x.onclick=()=>{answer(x.textContent);$('#ask-input').value=x.textContent});
renderCategories();updateFavorites();
